- name: create symfony project directory
  file: >
    path="{{ item.root_directory }}"
    state=directory
    owner="{{ item.root_directory_owning_user | default(symfony_web_server_user) }}"
    group="{{ item.root_directory_owning_group | default(symfony_web_server_group) }}"
    mode=0775
    recurse=true
  sudo: yes
  with_items: "{{ symfony_websites }}"