---
dependencies: []

galaxy_info:
  author: lesmyrmidons
  description: MongoDB for RedHat/CentOS/Debian 64Bit.
  company: ""
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: RedHat
    versions:
    - all
  categories:
    - database:nosql