---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=1.5
  - ANSIBLE_VERSION=1.6
  - ANSIBLE_VERSION=1.7
  - ANSIBLE_VERSION=1.8
  - ANSIBLE_VERSION=1.9.1

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION

  # Add ansible.cfg to pick up roles path.
  - printf "[defaults]\nroles_path = ../" > ansible.cfg

  # Run the galaxy install
  - ansible-galaxy install -r tests/galaxy.txt

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo -vvvv

notifications:
  email: false
