---
galaxy_info:
  author: mjanser
  description: Configures a Symfony applications
  license: MIT
  min_ansible_version: 1.6
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - web
dependencies: []
