---
# - name: "groups_to_create debug"
#   debug:
#     var: groups_to_create

- name: "Creating groups"
  group: name="{{item.name}}" gid="{{item.gid | default(omit)}}"
  with_items: "{{ groups_to_create }}"

- name: "Per-user group creation"
  group: name="{{item.username}}"
         gid="{{item.gid if item.gid is defined else item.uid}}"
  with_items: "{{ users }}"
  when: "{{ users_create_per_user_group }}"

- name: "User creation"
  user:
    name: "{{item.username}}"
    group: "{{item.username if users_create_per_user_group else users_group}}"
    # empty string removes user from all secondary groups
    groups: "{{item.groups | join(',') if 'groups' in item else ''}}"
    shell: "{{item.shell if item.shell is defined else users_default_shell}}"
    password: "{{item.password if item.password is defined else '!'}}"
    comment: "{{item.name if item.name is defined else ''}}"
    uid: "{{item.uid}}"
    createhome: "{{'yes' if users_create_homedirs else 'no'}}"
  with_items: "{{ users }}"

- name: "SSH keys"
  authorized_key:
    user: "{{item.0.username}}"
    key: "{{item.1}}"
    path: "/home/{{item.0.username}}/.ssh/authorized_keys"
  with_subelements:
    - "{{ users }}"
    - ssh_key

- name: "Setup user profiles"
  blockinfile:
    block: "{{item.profile}}"
    dest: "/home/{{item.username}}/.profile"
    owner: "{{item.username}}"
    group: "{{item.username}}"
    mode: 0644
    create: true
  when: users_create_homedirs and item.profile is defined
  with_items: "{{ users }}"

- name: "Deleted user removal"
  user: name="{{item.username}}" state=absent
  with_items: "{{ users_deleted }}"

- name: "Deleted per-user group removal"
  group: name="{{item.username}}" state=absent
  with_items: "{{ users_deleted }}"
  when: users_create_per_user_group
