---

- hosts: all
  sudo: yes
  roles:
    - franklinkim.logrotate
  vars:
    logrotate_scripts:
      - name: syslog
        path: /var/log/syslog
        options:
          - daily
          - compress
          - rotate 6
          - missingok
          - copytruncate
          - delaycompress
